# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Job.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Task_pb2 as Task__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Job.proto',
  package='ZmqUtil',
  syntax='proto3',
  serialized_pb=_b('\n\tJob.proto\x12\x07ZmqUtil\x1a\nTask.proto\";\n\x03Job\x12\x1b\n\x04task\x18\x01 \x01(\x0b\x32\r.ZmqUtil.Task\x12\x17\n\x0ftarget_addition\x18\x02 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[Task__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='ZmqUtil.Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='ZmqUtil.Job.task', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_addition', full_name='ZmqUtil.Job.target_addition', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=93,
)

_JOB.fields_by_name['task'].message_type = Task__pb2._TASK
DESCRIPTOR.message_types_by_name['Job'] = _JOB

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), dict(
  DESCRIPTOR = _JOB,
  __module__ = 'Job_pb2'
  # @@protoc_insertion_point(class_scope:ZmqUtil.Job)
  ))
_sym_db.RegisterMessage(Job)


# @@protoc_insertion_point(module_scope)
