# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DistributorMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DistributorMessage.proto',
  package='zmq_if',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x44istributorMessage.proto\x12\x06zmq_if\"\x8f\x01\n\x12\x44istributorMessage\x12\x10\n\x08redis_ip\x18\x01 \x01(\t\x12\x12\n\nredis_port\x18\x02 \x01(\x05\x12\x12\n\nchecker_ip\x18\x03 \x01(\t\x12\x14\n\x0c\x63hecker_port\x18\x04 \x01(\x05\x12\x10\n\x08localURL\x18\x05 \x01(\t\x12\x17\n\x0ftask_descriptor\x18\x06 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DISTRIBUTORMESSAGE = _descriptor.Descriptor(
  name='DistributorMessage',
  full_name='zmq_if.DistributorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='redis_ip', full_name='zmq_if.DistributorMessage.redis_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redis_port', full_name='zmq_if.DistributorMessage.redis_port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checker_ip', full_name='zmq_if.DistributorMessage.checker_ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checker_port', full_name='zmq_if.DistributorMessage.checker_port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='localURL', full_name='zmq_if.DistributorMessage.localURL', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_descriptor', full_name='zmq_if.DistributorMessage.task_descriptor', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['DistributorMessage'] = _DISTRIBUTORMESSAGE

DistributorMessage = _reflection.GeneratedProtocolMessageType('DistributorMessage', (_message.Message,), dict(
  DESCRIPTOR = _DISTRIBUTORMESSAGE,
  __module__ = 'DistributorMessage_pb2'
  # @@protoc_insertion_point(class_scope:zmq_if.DistributorMessage)
  ))
_sym_db.RegisterMessage(DistributorMessage)


# @@protoc_insertion_point(module_scope)
